CREATE TABLE `cf02882_fox`.`students` ( `ID` INT NOT NULL AUTO_INCREMENT , `FULL_NAME` VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL , `DATE_BIRTH` DATETIME NOT NULL , `MIDDLE_SCORE` FLOAT NOT NULL , `AVATAR` BLOB NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;

INSERT INTO `students` (`ID`, `FULL_NAME`, `DATE_BIRTH`, `MIDDLE_SCORE`) VALUES (NULL, 'Иванов', '1998-07-01 00:00:00', '3') 
